apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-var-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.var.claim.size }}
  storageClassName: local-storage
  volumeName: {{ .Release.Name }}-usb-stick-var-pv