apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: {{ .Release.Name }}-usb-stick-var-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: {{ .Values.storage.var.volume.size }}
  local:
    path: {{ .Values.storage.var.volume.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - agt01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
status:
  phase: Available