image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

schedule: "* * * * *"

secrets:
  idRsa: "personal-id-rsa"
  webServerCreds: "web-server-creds"
