kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "dhcpd.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - {{ include "dhcpd.fullname" . }}-security-policy