apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dhcpd.fullname" . }}-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ include "dhcpd.fullname" . }}-security-policy