apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: {{ include "dhcpd.fullname" . }}-usb-stick-data-pv
spec:
  accessModes:
  - {{ .Values.storage.accessMode }}
  capacity:
    storage: {{ .Values.storage.data.volume.size }}
  local:
    path: {{ .Values.storage.data.volume.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - agt01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
status:
  phase: Available