image:
  repository: busybox
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

schedule: "30 3 * * *"

secrets:
  idRsa: "personal-id-rsa"
  webServerCreds: "web-server-creds"
