apiVersion: v1
kind: Pod
metadata:
    name: {{ include "mongodb.fullname" . }}-initializer
spec:
    containers:
      - name: {{ include "mongodb.fullname" . }}-initializer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: [ 'bash', '-c', '{{ include "mongodb.cluster_init" . }}' ]