apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edge-proxy.name" . }}-nginx-config
data:
  nginx.conf: |
    upstream k3s {
      server 10.1.255.253;
      server 10.1.255.252;
    }

    # Default server configuration
    #
    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }
    
    server {
      listen       80;
      listen  [::]:80;
      server_name  _;

      # access_log  /var/log/nginx/host.access.log  main;

      location / {
        proxy_pass http://k3s;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded_For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
      }

      #error_page  404              /404.html;

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
