apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edge-proxy.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "edge-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "edge-proxy.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "nginx:1.21.4"
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
            readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "edge-proxy.name" . }}-nginx-config
